# Generated by Django 4.1.4 on 2022-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_de_la_empresa', models.CharField(max_length=250, verbose_name='Empresa')),
                ('numero_de_ruc', models.CharField(max_length=250, verbose_name='RUC')),
                ('nombre_del_nexo', models.CharField(max_length=250, verbose_name='Nexo')),
                ('telefono_del_nexo', models.CharField(max_length=250, verbose_name='Tel. Nexo')),
                ('mail_del_nexo', models.CharField(max_length=250, verbose_name='Mail Nexo')),
                ('nombre_contacto_pagos', models.CharField(max_length=250, verbose_name='Contacto de pago')),
                ('telefono_contacto_pagos', models.CharField(max_length=250, verbose_name='Tel. Conacto Pago')),
                ('mail_contacto_pagos', models.CharField(max_length=250, verbose_name='Mail Conacto Pago')),
                ('fecha_de_vinculacion', models.DateField(verbose_name='Fecha de Vinculacion')),
                ('notas_adicionales', models.CharField(max_length=250, verbose_name='Notas')),
                ('forma_de_pago_habitual', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Cheque'), ('3', 'Transferencia'), ('4', 'Deposito')], max_length=20, verbose_name='Pago Habitual')),
                ('banco', models.CharField(max_length=250, verbose_name='Banco')),
                ('titular_de_la_cuenta', models.CharField(max_length=250, verbose_name='Titular de la cuenta')),
                ('tipo_de_cuenta', models.CharField(choices=[('Corriente', 'Corriente'), ('Ahorro', 'Ahorro'), ('Chequera', 'Chequera'), ('Nomina', 'Nomina'), ('Dolares', 'Dolares')], max_length=250, verbose_name='Tipo de Cuenta')),
                ('numero_de_cuenta', models.CharField(max_length=250, verbose_name='Nro de Cuenta')),
                ('documento_de_cuenta', models.CharField(max_length=250, verbose_name='Documento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
