# Generated by Django 4.1.4 on 2022-12-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymes', '0002_alter_cliente_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono_contacto_pagos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tel. Conacto Pago'),
        ),
    ]
