# Generated by Django 4.1.4 on 2022-12-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rubrod'),
        ('pymes', '0006_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.rubrod'),
        ),
    ]
