# Generated by Django 4.1.4 on 2022-12-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfileD',
            fields=[
                ('staff_no', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.TextField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('reporting_officer', models.IntegerField()),
            ],
        ),
    ]
