# Generated by Django 4.1.4 on 2022-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentoD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('staff_name', models.TextField(max_length=200, verbose_name='Nombre de departamento')),
                ('jerarquia', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20, verbose_name='Jerarquia asignada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('staff_no', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.TextField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('reporting_officer', models.IntegerField()),
            ],
        ),
    ]
